# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '.github/workflows/test.yml'
      - 'deno.jsonc'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'

permissions:
  contents: read

env:
  DENO_VERSION: 1.x

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check
        run: deno task check

      - name: Run linter
        run: deno task lint

  jsr-publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: deno publish --dry-run

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: |
            deno run -A ./mod.ts
        env:
          DEBUG: true
          PACKAGE_NAME: '@ryoppippi/limo'
          PACKAGE_VERSION: '0.1.2'
          PACKAGE_DESCRIPTION: 'example'
          NPM_CONFIG_PROVENANCE: '--dry-run'

  action-timeline:
    needs: 
      - ci
      - jsr-publish-dry-run
      - test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@44c9c178ffb2fb1d9859614a3ffa79ccfb77565e # v3.1.0
