# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deno Test

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '.github/workflows/test.yml'
      - 'deno.jsonc'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'

permissions:
  contents: read

env:
  DENO_VERSION: 1.x

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check
        run: deno task check

      - name: Run linter
        run: deno task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Run test with coverage report
        shell: bash
        run: |
          deno task test:coverage
          deno task coverage:lco
          deno task coverage:show >> .coverage/result.txt

      - name: Upload coverage report to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./.coverage

  coverage-report:
    needs:
      - ci
      - test
    if: false # if you want to upload coverage report to Codecov, set to true
    runs-on: ubuntu-latest
    permissions:
      write-all
    steps:
      - name: Download coverage report from Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./.coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          file: ./.coverage/lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}

  jsr-publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: deno publish --dry-run

  action-timeline:
    needs: 
      - ci
      - test
      - coverage-report
      - jsr-publish-dry-run
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
